PetShop/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PetShop.Data;
using PetShop.Models;

namespace PetShop.Controllers
{
    public class AdministratorController : Controller
    {

        private PetShopContext _DbpetShopContext;

        public AdministratorController(PetShopContext DbpetShopContext)
        {
            _DbpetShopContext = DbpetShopContext;
        }

        public IActionResult Home()
        {

            IEnumerable<Animals> Allanimals = (from objAnimal in _DbpetShopContext.Animals

                                               select new Animals()
                                               {
                                                   AnimalID = objAnimal.AnimalID,
                                                   Name = objAnimal.Name,
                                                   Age = objAnimal.Age,
                                                   PictureName = objAnimal.PictureName,
                                                   Description = objAnimal.Description,
                                                   CategoryID = objAnimal.CategoryID,
                                                   CommentID = objAnimal.CommentID

                                               }).ToList();

            ViewBag.categories = _DbpetShopContext.Categories.ToList();

           




            return View(Allanimals);
        }

        public IActionResult ByCategories(int id)
        {
            IEnumerable<Animals> Animals = (from objAnimal in _DbpetShopContext.Animals
                                            where objAnimal.CategoryID == (int)id
                                            select new Animals()
                                            {
                                                AnimalID = objAnimal.AnimalID,
                                                Name = objAnimal.Name,
                                                Age = objAnimal.Age,
                                                PictureName = objAnimal.PictureName,
                                                Description = objAnimal.Description,
                                                CategoryID = objAnimal.CategoryID,
                                                CommentID = objAnimal.CommentID

                                            }).ToList();
            ViewBag.categories = _DbpetShopContext.Categories.ToList();
            return View(Animals);





        }

        public IActionResult Delete(int id)
        {

            var Animal = _DbpetShopContext.Animals.Where(a => a.AnimalID == id);
            Animals AnimarForRemovie = Animal.FirstOrDefault();
            _DbpetShopContext.Animals.Remove(AnimarForRemovie);
            _DbpetShopContext.SaveChanges();
             return RedirectToAction("Home");
        }
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.categories = _DbpetShopContext.Categories.ToList();
            return View();

        }

        [HttpPost]
        public IActionResult Add(Animals animal)
        {

            Animals NewAnimal = new Animals
            {
                Name = animal.Name,
                Age = animal.Age,
                PictureName = animal.PictureName,
                Description = animal.Description,
                CategoryID = animal.CategoryID


            };


            _DbpetShopContext.Animals.Add(NewAnimal);
            _DbpetShopContext.SaveChanges();

            return RedirectToAction("Home");

        }
        
        public IActionResult Edit(int animalID)
        {
            var AnimalRec= (from item in _DbpetShopContext.Animals
                           where item.AnimalID==animalID
                           select item).First();

            TempData["imgPatch"] = AnimalRec.PictureName;
            ViewBag.categories = _DbpetShopContext.Categories.ToList();
            ViewBag.SpecificCategoryName = _DbpetShopContext.Categories.Where(c => c.CategoryID == AnimalRec.CategoryID).Select(c => c.Name).FirstOrDefault();
            ViewBag.SpecificCategoryID = _DbpetShopContext.Categories.Where(c => c.CategoryID == AnimalRec.CategoryID).Select(c => c.CategoryID).FirstOrDefault();
            return View("Edit",AnimalRec);



        }

        [HttpPost]
        public IActionResult Edit(Animals obj)
        {
            var AnimalRec = (from item in _DbpetShopContext.Animals
                             where item.AnimalID == obj.AnimalID
                             select item).First();

            AnimalRec.Name = obj.Name;
            AnimalRec.Age = obj.Age;
            AnimalRec.PictureName = TempData["imgPatch"].ToString();
            AnimalRec.Description = obj.Description;
            AnimalRec.CategoryID = obj.CategoryID;
           _DbpetShopContext.SaveChanges();


            return RedirectToAction("Home");

        }

    }
}

PetShop/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PetShop.Data;
using PetShop.Models;




namespace PetShop.Controllers
{
    public class UserController : Controller
    {
        private PetShopContext _DbpetShopContext;

        public UserController(PetShopContext DbpetShopContext)
        {
            _DbpetShopContext = DbpetShopContext;
        }

        public IActionResult Home()
        {


         var Animals = (from a in _DbpetShopContext.Animals
                                                from c in _DbpetShopContext.Comments
                                                where c.AnimalID == a.AnimalID
                                                group a by a.AnimalID into gr                                             
                                                select new
                                                {
                                                   animalID=gr.Key,
                                                   count=gr.Count()

                                                }).ToList();


            List<int> IDOfTop2dAnimals = Animals
                                    .OrderByDescending(a => a.count)
                                    .Take(2)
                                    .Select(a=>a.animalID)
                                    .ToList();
    
            IEnumerable<Animals> Top2animals = (from objAnimal in _DbpetShopContext.Animals
                                       where IDOfTop2dAnimals.Contains(objAnimal.AnimalID)
                                       select new Animals()
                                       {
                                           AnimalID = objAnimal.AnimalID,
                                           Name = objAnimal.Name,
                                           Age = objAnimal.Age,
                                           PictureName = objAnimal.PictureName,
                                           Description = objAnimal.Description,
                                           CategoryID = objAnimal.CategoryID,
                                           CommentID = objAnimal.CommentID

                                       }).ToList();

            return View(Top2animals);
        }

        public IActionResult Catalog()
        {

            IEnumerable<Animals> Allanimals = (from objAnimal in _DbpetShopContext.Animals

                                               select new Animals()
                                               {
                                                   AnimalID = objAnimal.AnimalID,
                                                   Name = objAnimal.Name,
                                                   Age = objAnimal.Age,
                                                   PictureName = objAnimal.PictureName,
                                                   Description = objAnimal.Description,
                                                   CategoryID = objAnimal.CategoryID,
                                                   CommentID = objAnimal.CommentID

                                               }).ToList();

            ViewBag.categories = _DbpetShopContext.Categories.ToList();
            return View(Allanimals);

        }

        public IActionResult ByCategories(int id)
        {
            IEnumerable<Animals> Animals = (from objAnimal in _DbpetShopContext.Animals
                                            where objAnimal.CategoryID == (int)id
                                            select new Animals()
                                            {
                                                AnimalID = objAnimal.AnimalID,
                                                Name = objAnimal.Name,
                                                Age = objAnimal.Age,
                                                PictureName = objAnimal.PictureName,
                                                Description = objAnimal.Description,
                                                CategoryID = objAnimal.CategoryID,
                                                CommentID = objAnimal.CommentID

                                            }).ToList();
            ViewBag.categories = _DbpetShopContext.Categories.ToList();
            return View(Animals);


        }

        public IActionResult AnimalInfo(int id)
        {

            var IfExixtsComment = _DbpetShopContext.Comments.Where(c => c.AnimalID == id).ToList();

            if (IfExixtsComment == null)
            {
                ViewBag.Comment = "No Comments !";
            }

            List<Comments> comments = IfExixtsComment;
            ViewBag.Comment = comments;
            Animals ani = _DbpetShopContext.Animals.SingleOrDefault(a => a.AnimalID == id);
            ViewBag.AnimalID = id;
            Categories catego = _DbpetShopContext.Categories.SingleOrDefault(ca => ca.CategoryID == ani.CategoryID);
            ViewBag.categoryName = catego.Name;

            return View(ani);

        }

        public IActionResult AddComments (string comment, int id)
        {
           

            Comments newComment = new Comments();
            newComment.AnimalID = id;
            newComment.Comment = comment;
            _DbpetShopContext.Comments.Add(newComment);
            _DbpetShopContext.SaveChanges();
            return RedirectToAction("AnimalInfo", new { id = id });

        }

    }
}

PetShop/Views/Administrator/Add.cshtml
@model PetShop.Models.Animals
@{
   
}




@using (Html.BeginForm())
{

<div class="form-group" id="con">

    <form>

      <br />
      <h5>Form to Add New Animal</h5>
      <br />

       <div>
       @Html.LabelFor(model => model.Name)
       </div>
       <div>
       @Html.EditorFor(model => model.Name)
       </div>


            <div>
                @Html.LabelFor(model => model.Age)
            </div>
            <div>
                @Html.EditorFor(model => model.Age)
            </div>




            <div>
                @Html.LabelFor(model => model.PictureName)
            </div>
            <div>
                <input type="file" name="ImageFile"/>
            </div>



            <div>
                @Html.LabelFor(model => model.Description)
            </div>
            <div>
                @Html.TextAreaFor(model => model.Description)
            </div>


            <div>
                @Html.LabelFor(model => model.Category)
            </div>
            <div>
                <select id="addCatagory" name="categoryID">
                    @foreach (Categories item in @ViewBag.categories)
                    {
                        <option value="@item.CategoryID" ,selected="selected">@item.Name</option>

                    }
                </select>
            </div>
            <br />
            <p>
                <input type="submit" value="Add new Animal" />
            </p>


        

    </form>

     </div>



}

PetShop/Views/Administrator/ByCategories.cshtml
@model IEnumerable<PetShop.Models.Animals>


@{

}

<br />

<select onchange="location = this.value;">
    @foreach (Categories item in @ViewBag.categories)
    {
        <option value="/Administrator/ByCategories/@item.CategoryID?limit=50" , selected="selected">@item.Name</option>

    }
</select>
<div style="padding-left:610px">

    <input type="button" class="btn-outline-primary" id="add" value="Add New Animal" style="background-color:greenyellow;" onclick="location.href='@Url.Action("Add", "Administrator")'" />

</div>

<div class="container">

    <div class="row">
        <div class="col-12">


            <table class="table table-image" style="width:1000px;">


                <thead>
                    <tr>
                        <th scope="col">Portrait</th>
                        <th scope="col">Name</th>
                        <th scope="col">For more information</th>

                    </tr>

                </thead>


                <tbody>



                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width:100px">
                                <img class="img-fluid img-thumbnail" style="height:80px;width:100px;" src="@Url.Content(@item.PictureName)" />
                            </td>
                            <td style="width:100px">@item.Name</td>
                            <td style="width:100px">

                                <input type="button" class="btn-outline-primary" style="color:black" value="Details" onclick="location.href='@Url.Action("AnimalInfo", "User", new { id = item.AnimalID })'" />
                                <input type="button" class="btn-outline-primary" style="color:black;background-color:red" value="Delete" onclick="location.href='@Url.Action("Delete", "Administrator", new { id = item.AnimalID })'" />
                                <input type="button" class="btn-outline-primary" style="color:black;background-color:khaki" value="Edit" onclick="location.href='@Url.Action("Edit", "Administrator", new {item.AnimalID })'" />

                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
    </div>

</div>

PetShop/Views/Administrator/Edit.cshtml
@model PetShop.Models.Animals
@{

}

@{
    ViewData["Title"] = "Edit";
}

<br />
@using (Html.BeginForm())
{

    <div class="form-group" id="con">

        <form action="Edit/Administrator" method="post">

            <br />
            <h5>Form to Edit Animal info</h5>
            <br />

            <div>
                @Html.LabelFor(model => model.Name)
            </div>
            <div>
                @Html.TextBoxFor(model => model.Name)
            </div>


            <div>
                @Html.LabelFor(model => model.Age)
            </div>
            <div>
                @Html.TextBoxFor(model => model.Age)
            </div>




            <div>
                @Html.LabelFor(model => model.PictureName)
            </div>
            <div>
                <img src="@Url.Content(Model.PictureName)"style="height:40px;width:50px;" />
                <input type="file" name="ImageFile" id="file" />
            </div>



            <div>
                @Html.LabelFor(model => model.Description)
            </div>
            <div>
                @Html.TextAreaFor(model => model.Description)
            </div>


            <div>
                @Html.LabelFor(model => model.Category)
            </div>
            <div>
                <select id="addCatagory" name="categoryID">

                    <option value="@ViewBag.SpecificCategoryID" selected>@ViewBag.SpecificCategoryName </option>

                    @foreach (Categories item in @ViewBag.categories)
                    {
                        <option value="@item.CategoryID">@item.Name</option>

                    }

                </select>
            </div>
            <br />
            <p>
                <input type="submit" value="Edit Animal" />
            </p>




        </form>

    </div>



}

PetShop/Views/Administrator/Home.cshtml
@model IEnumerable<PetShop.Models.Animals>


@{

}

<br />

<select onchange="location = this.value;">

    @foreach (Categories item in @ViewBag.categories)
    {
        <option value="/Administrator/ByCategories/@item.CategoryID?limit=50" , selected="selected">@item.Name</option>

    }


</select>


    <input type="button"  id="add" value="Add New Animal" onclick="location.href='@Url.Action("Add", "Administrator")'" />


<div class="container">

    <div class="row">
        <div class="col-12">


            <table class="table table-image" style="width:1000px;">


                <thead>
                    <tr>
                        <th scope="col">Portrait</th>
                        <th scope="col">Name</th>
                        <th scope="col">For more information</th>

                    </tr>

                </thead>


                <tbody>



                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width:100px">
                                <img class="img-fluid img-thumbnail" style="height:80px;width:100px;" src="@Url.Content(@item.PictureName)" />
                            </td>
                            <td style="width:100px">@item.Name</td>
                            <td style="width:100px">

                                <input type="button" class="btn-outline-primary" style="color:black" value="Details" onclick="location.href='@Url.Action("AnimalInfo", "User", new { id = item.AnimalID })'" />
                                <input type="button" class="btn-outline-primary" style="color:black;background-color:red" value="Delete" onclick="location.href='@Url.Action("Delete", "Administrator", new { id = item.AnimalID })'" />
                                <input type="button" class="btn-outline-primary" style="color:black;background-color:khaki" value="Edit" onclick="location.href='@Url.Action("Edit", "Administrator", new {item.AnimalID })'" />

                            </td>
                        </tr>
                    }
                </tbody>

            </table>

        </div>
    </div>

</div>